image: zivgitlab.wwu.io/ml-de/teaching/ps-housetech/ps-housetech-backend:node20

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

before_script:
  - npm install

include:
  - ".gitlab/*.yaml"
